### ISSUE TITLE
Generalize to coupled IDEs

### ISSUE THREAD

**Issue by AlexSchuckert** [JoshKarpel/idesolver#28]
Thanks very much for this amazing IDE solver. In physics applications, often coupled IDEs appear, i.e. y is a vector and c(y), F(y) couple the different components of y. Is it possible to generalize this solver to this case?

**Comment by JoshKarpel** [comment]
Hi Alex, thanks for the question! I'm honestly not sure how hard it would be to generalize to that case. It could range from "just need to tweak how we pass arguments to the underlying `scipy` methods" to "needs a total redesign" to "the algorithm isn't stable on coupled IDEs".

Do you have a simplified example of such an IDE that you'd like to solve, preferably with an analytic solution?

Warning: I have relatively limited time to work on IDESolver right now. If you have time contribute, I'd be happy to accept a PR!

**Comment by nbrucy** [comment]
Hello,
I also want to thanks you for this excellent and well written piece of software. 

To what regards the issue, I is more "just need to tweak how we pass arguments to the underlying `scipy` methods".
I added a PR (#35 ) doing this. It still fails at one test (where it actually should fail but the exception is not properly caught).
