### ISSUE TITLE
Invalid syntax in idesolver.py

### ISSUE THREAD

**Issue by iljah** [JoshKarpel/idesolver#4]
After doing a `pip3 install --user idesolver` and trying to import idesolver in python3 I get:
```
Python 3.5.4 (default, Oct  9 2017, 12:07:29) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from idesolver import IDESolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.local/lib/python3.5/site-packages/idesolver/__init__.py", line 1, in <module>
    from .idesolver import *
  File ".../.local/lib/python3.5/site-packages/idesolver/idesolver.py", line 257
    logger.debug(f'Advanced to iteration {self.iteration}. Current error: {error_current}.')
                                                                                          ^
SyntaxError: invalid syntax
```
while in python2 I get (installed with pip instead of pip3):
```
Python 2.7.13 (default, Dec  1 2017, 09:21:53) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from idesolver import IDESolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.local/lib/python2.7/site-packages/idesolver/__init__.py", line 1, in <module>
    from .idesolver import *
  File ".../.local/lib/python2.7/site-packages/idesolver/idesolver.py", line 40
    def complex_quad(integrand: Callable, lower_bound: float, upper_bound: float, **kwargs) -> (complex, float, float, tuple, tuple):
                              ^
SyntaxError: invalid syntax
```

**Comment by JoshKarpel** [comment]
Both of these are results of IDESolver being Python 3.6+ only, because I use f-strings. I'd like to keep this requirement unless there are strong objections.

**Comment by arghdos** [comment]
@JoshKarpel neat! I didn't know about fstrings -- I typically use a `Template` that `safe_substitute`'s `**locals` (which has it's obvious disadvantages).  You might consider adding [future-fstrings](https://github.com/asottile/future-fstrings) or the like for Python < 3.6 for backwards compatibility

**Comment by JoshKarpel** [comment]
I spent some time today investigating backwards-compatibility options. Switching to `.format()` does allow for compatibility with 3.5, but IDESolver is still not compatible with <=3.4 because I use the `typing` module for type annotations.

I would rather not give up f-strings and type annotations, which dramatically improve the quality of the code, to gain backwards-compatibility for just a few versions. I don't know of anyone still using <=3.3 that isn't on 2.7, which I have no interest in doing compatibility for. Most users should be able to upgrade from 3.4-5 to 3.6 without trouble. Thoughts?

**Comment by iljah** [comment]
Requiring python >= 3.6 should be fine but the error message for < 3.6 users should be improved. Even better if pip refuses to install the program when running python < 3.6.

**Comment by JoshKarpel** [comment]
> Requiring python >= 3.6 should be fine but the error message for < 3.6 users should be improved. Even better if pip refuses to install the program when running python < 3.6.

Very good idea. https://github.com/JoshKarpel/idesolver/commit/75790d21c7e96514add92abb1e2a9083f00b76b4 adds a checks to the `setup.py` that gives an error message if trying to install on Python <3.6

**Comment by arghdos** [comment]
@JoshKarpel that looks like a good compromise

**Comment by iljah** [comment]
I only tested that 2.7.14 gave a clear error, thanks.
