### ISSUE TITLE
Relicense to BSD (adding IDEsolver to SciPy)

### ISSUE THREAD

**Issue by franktoffel** [JoshKarpel/idesolver#8]
I know that the original author published his code with a GPL3 license.

But, have you tried to contact him? Maybe he has no problem changing the license to BSD-3 so you can add this superb code into SciPy.

**Comment by JoshKarpel** [comment]
Thanks for your kind words!

Unfortunately, I don't think IDESolver is a good fit for SciPy at the moment. I used a lot of features that are Python 3.5/3.6+ only, and SciPy is still maintaining compatibility with Python 2.6+, as far as I'm aware. I think that going back that far would seriously degrade the quality of the code.

**Comment by franktoffel** [comment]
Well, if I were you I would try to reach the main author so his code (and yours) has a higher impact in the near future ;)

As you might know, [most of the scientific libraries will drop support for Python 2.7 in 2020](http://www.python3statement.org/), including NumPy.

**Comment by JoshKarpel** [comment]
Fair point, and I'm certainly open to revisiting this in the future. 2020 is still a long way away :)
